### ISSUE TITLE
Tests will not run

### ISSUE THREAD

**Issue by smcgrat** [campsych/concerto-platform#186]
Can anyone point out what I have done wrong here please. It is probably something simple and obvious, so sorry about that. Many thanks in advance.

### Concerto Platform version
v5.0.beta.2.186

### Expected behavior
Clicking Run Test leads to the test running.

### Actual behavior
Test does not run!

Web page displays ``Please wait...`` and does not load the test. Here is the entry from the relevant apache access log:
```
192.168.0.1 - - [31/May/2018:11:01:58 +0100] "POST /test/flowmq/session/start/%5B%5D HTTP/1.1" 404 539 "http://hostname.fqdn/app.php/test/flowmq" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36"
```

### Steps to reproduce the issue

- Setup concerto as per https://github.com/campsych/concerto-platform/wiki/Linux-installation
- Here are the relevant redacted configuration settings, I hope all that are needed anyway
- ``/var/www/vhosts/concerto/app/config/parameters.yml``
```
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: concerto
    database_user: concerto
    database_password: 'my super secret password'
    database_path: null
    database_unix_socket: null
    test_database_name: concerto_test
    test_database_user: concerto
    test_database_password: 'my super secret password'
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en_GB
    secret: my super secret secret
```
- ``/var/www/vhosts/concerto/app/config/parameters_nodes.yml``
```
# This file is auto-generated during the composer install
parameters:
    nodes:
        -
            id: local
            protocol: http
            ip: 127.0.0.1
            host: localhost
            dir: /
            connection: local
            hash: 'snip'
            'snip more
```
- ``/var/www/vhosts/concerto/app/config/parameters_test_runner.yml``
```
# This file is auto-generated during the composer install
parameters:
    test_runner_settings:
        max_idle_time: 3900
        max_execution_time: 30
        keep_alive_interval_time: 120
        keep_alive_tolerance_time: 490
        r_environ_path: null
        php_exec: php
        rscript_exec: Rscript
```
- ``/var/www/vhosts/concerto/app/config/parameters_uio.yml``
```
# This file is auto-generated during the composer install
parameters:
    uio: {  }

```
