### ISSUE TITLE
Can't deploy with mysql-server 8.0

### ISSUE THREAD

**Issue by snaeil** [campsych/concerto-platform#318]
### Concerto Platform version
5.0.20

### Expected behavior
Deploy concerto with mysql-server 8.0 instead of 5.7

### Actual behavior
The logs show me an error and concerto won't be accessible:

```
Attaching to concerto
concerto      |      wait-for-it.sh: waiting 300 seconds for mysqldb:3306
concerto      |      wait-for-it.sh: mysqldb:3306 is available after 11 seconds
concerto      |      concerto setup (prod)
concerto      |      updating database...
concerto      |      09:46:46 ERROR     [console] Error thrown while running command "concerto:setup --env=prod --admin-pass=doof". Message: "An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client" ["exception" => Doctrine\DBAL\Exception\DriverException { …},"command" => "concerto:setup --env=prod --admin-pass=doof","message" => "An exception occurred in driver: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client"]
concerto      |      
concerto      |      In AbstractMySQLDriver.php line 106:
concerto      |                                                                                     
concerto      |        An exception occurred in driver: SQLSTATE[HY000] [2054] The server requeste  
concerto      |        d authentication method unknown to the client                                
concerto      |                                                                                     
concerto      |      
concerto      |      In PDOConnection.php line 31:
concerto      |                                                                                     
concerto      |        SQLSTATE[HY000] [2054] The server requested authentication method unknown t  
concerto      |        o the client                                                                 
concerto      |                                                                                     
concerto      |      
concerto      |      In PDOConnection.php line 27:
concerto      |                                                                                     
concerto      |        SQLSTATE[HY000] [2054] The server requested authentication method unknown t  
concerto      |        o the client                                                                 
concerto      |                                                                                     
concerto      |      
concerto      |      In PDOConnection.php line 27:
concerto      |                                                                                     
concerto      |        PDO::__construct(): The server requested authentication method unknown to t  
concerto      |        he client [caching_sha2_password]                                            
concerto      |                                                                                     
concerto      |      
concerto      |      concerto:setup [--admin-pass ADMIN-PASS] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
concerto      |      

```

### Steps to reproduce the issue
Try to deploy, by using the following docker-compose file with `docker-compose up -d`:

```yml
version: '2'

services:

  mysqldb:
    image: mysql/mysql-server:8.0
    container_name: mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_ONETIME_PASSWORD=true
      - MYSQL_DATABASE=concerto
      - MYSQL_USER=concerto
      - MYSQL_PASSWORD=not-so-secret
      - MYSQL_LOG_CONSOLE=true
    ports:
      - "13306:3306"

  concerto:
    image: campsych/concerto-platform:5.0.20
    container_name: concerto
    environment:
      - DB_HOST=mysqldb
      - DB_NAME=concerto
      - DB_USER=concerto
      - DB_PASSWORD=not-so-secret
    ports:
      - "8000:80"
      - "8443:443"
    depends_on:
      - mysqldb
```
