### ISSUE TITLE
Concerto sets id's data type incorrectly in database when deploying from content export

### ISSUE THREAD

**Issue by snaeil** [campsych/concerto-platform#323]
### Concerto Platform version
5.0.20

### Expected behavior
When deploying concerto, using a CONCERTO_CONTENT_URL, 
`export.concerto.yml` is used. Sometimes it's necessary to have a data table using a string as an ID.
Having data tables defined in `export.concerto.yml`, Concerto will create these in the database.

Following table should also be created as defined:

```yml
-                                             
  class_name: DataTable                       
  id: 19                           
  name: user          
  description: ''                                 
  accessibility: 2                                
  archived: '0'                               
  columns:                                     
    -                        
      name: id                           
      type: string                   
      nullable: false                     
      length: 255                        
    -                                         
      name: date_of_birth   
      type: date                    
      nullable: false      
      length: ''                           
    -                          
      ........
```

### Actual behavior

Concerto will create this table with an ID of type bigint, as we can see from adminer:
![Screenshot from 2021-01-18 14-46-21](https://user-images.githubusercontent.com/52743746/104923186-ff1fa900-599b-11eb-9d22-680499a86d5e.png)

### Steps to reproduce the issue

Unfortunately I was not able to create the table beforehands and deploy Concerto then. Concerto will not start because the table already exists.

That's why my reproducing steps are as follows:
1. Deploy concerto without the table
2. Create the table directly in database
3. add table name to table `DataTable` -> table is usable in Concerto now
4. export content (from Administration -> Content)
5. Set up database afresh without any tables
6. Check that the table appears with an D of type `String` in `export.concerto.yml`
7. Deploy Concerto
8. Check the database and find that the table was created with sql type `bigint`
